using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using MYSTORE.M_EntityFramework;
using MYSTORE.UI_FORM;

namespace MYSTORE.UI_FORM
{
    public partial class frm_Purchase0 : Form
    {
        #region init 

        Manege_StoreEntities4 db = new Manege_StoreEntities4();
        Suppoler supp = new Suppoler();
        public frm_Purchase0()
        {
            InitializeComponent();

            var rs2 = db.Suppolers.Select(x => x.Name).ToList();
            cmbsupp.DataSource = rs2;
            AutoCompleteStringCollection acsc2 = new AutoCompleteStringCollection();
            acsc2.AddRange(rs2.ToArray());
            cmbsupp.AutoCompleteCustomSource = acsc2;

            //        // This line of code is generated by Data Source Configuration Wizard
            //        // Instantiate a new DBContext
            //        MYSTORE.M_EntityFramework.Manege_StoreEntities1 dbContext = new MYSTORE.M_EntityFramework.Manege_StoreEntities1();
            //        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //        dbContext.purchases.LoadAsync().ContinueWith(loadTask =>
            //        {
            //// Bind data to control when loading complete
            //grid_Pinvoice.DataSource = dbContext.purchases.Local.ToBindingList();
            //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        #endregion

        #region go to ditalis 
        private void btn_add_Click(object sender, EventArgs e)
        {
            if (db.Suppolers.Any(x => x.Name == cmbsupp.Text))
            {
            frm_Purchase frm_Pur = new frm_Purchase();
                frm_Pur.txtsupp.Text = cmbsupp.Text;
                pnl_Pinvoice.Controls.Clear();
                pnl_Pinvoice.Controls.Add(frm_Pur.pnl_pur);
                frm_Pur.cmbprod1.Focus();
                frm_Pur.cmbprod1.Select();
            }
            else
            {
                MessageBox.Show(" !! هذا المورد غير موجود الرجاء إضافته", "Warring", MessageBoxButtons.OK, MessageBoxIcon.Warning);

            }


        }

        private void cmbsupp_SelectedIndexChanged(object sender, EventArgs e)
        {
            supp = db.Suppolers.Where(x => x.Name == cmbsupp.Text).FirstOrDefault();

            var qu = from p in db.purchases
                     where p.Supp_ID == supp.Supp_ID
                     select new { p.Pur_ID, p.Date, p.TotalPrice };
            grid_Pinvoice.DataSource = qu.ToList();
            txtsum.Text = qu.Sum(x => x.TotalPrice).ToString();
        }
        #endregion

    }
}
