//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSTORE.M_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debtor
    {
        public int ID { get; set; }
        public Nullable<int> Supp_ID { get; set; }
        public Nullable<double> batches { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Suppoler Suppoler { get; set; }
    }
}
