//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSTORE.M_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.purchases_Detile = new HashSet<purchases_Detile>();
        }
    
        public int Pur_ID { get; set; }
        public Nullable<int> Supp_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Suppoler Suppoler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchases_Detile> purchases_Detile { get; set; }
    }
}
