//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSTORE.M_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchases_Detile
    {
        public int ID { get; set; }
        public Nullable<int> Prod_ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Pur_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> NPrice { get; set; }
        public Nullable<double> SPrice { get; set; }
        public Nullable<double> sumion { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
